---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin-delete-db-configmap
  namespace: buzzim-admin
data:
  # https://www.postgresql.org/docs/10/libpq-envars.html
  PGHOST: "stolon-proxy-service.stolon.svc.cluster.local"
  PGPORT: "5432"
  PGUSER: "stolon"

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-admin-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin-delete-db-secret
  namespace: buzzim-admin
type: Opaque
data:
  # https://www.postgresql.org/docs/10/libpq-envars.html
  PGPASSWORD: BUZZ_IM_ADMIN_DB_PASSWORD

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin-delete-db
  namespace: buzzim-admin
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: buzzim-admin-delete-db
        image: postgres:10.5-alpine

        command: ["/bin/sh", "-c"]
        args:
        - psql --command "DROP DATABASE $BUZZIM_ADMIN_DB_DATABASE;" postgres &&
          psql --command "DROP ROLE $BUZZIM_ADMIN_DB_USER;" postgres
        envFrom:
        - configMapRef:
            name: buzzim-admin-configmap
        - configMapRef:
            name: buzzim-admin-delete-db-configmap
        - secretRef:
            name: buzzim-admin-delete-db-secret

      restartPolicy: Never
