---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-admin-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin
  namespace: buzzim-admin
spec:
  type: NodePort
  selector:
    app: buzzim-admin
  ports:
  - name: http
    protocol: TCP
    targetPort: admin-http
    port: 11080
    nodePort: 32741
