---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-admin-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin
  namespace: buzzim-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buzzim-admin
  serviceName: buzzim-admin

  template:
    metadata:
      labels:
        app: buzzim-admin
    spec:
      restartPolicy: Always
      containers:
      - name: buzzim-admin
        image: dialogicbuzz/buzzim-admin:4.0.0.64

        envFrom:
        - configMapRef:
            name: buzzim-admin-configmap
        - secretRef:
            name: buzzim-admin-secret
        - secretRef:
            name: buzzim-admin-tls-secret
            optional: true

        ports:
          - name: admin-http
            protocol: TCP
            containerPort: 11080

