---
# Values are Base64 encoded, use base64 -w0
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: buzzim-admin
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-admin-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-admin-secret
  namespace: buzzim-admin
type: Opaque
data:
  BUZZIM_ADMIN_DB_PASSWORD: 
  APNS_CERT: 
  GCM_API_KEY: 
