kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: buzzim-deploy-clusterrole
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["namespaces", "configmaps", "secrets", "statefulsets", "services", "ingresses"]
  verbs: ["get", "watch", "list", "create", "update", "patch"]
