---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: buzzim-deploy
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-deploy-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-deploy
  namespace: buzzim-deploy
spec:
  type: NodePort
  selector:
    app: buzzim-deploy
  ports:
  - name: http
    protocol: TCP
    targetPort: deploy-http
    port: 11081
    nodePort: 32744
