---
# Values are Base64 encoded, use base64 -w0
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: buzzim-deploy
    app.kubernetes.io/version : '1.0.0'
    app.kubernetes.io/component: im-deploy-service
    app.kubernetes.io/part-of: buzzim
  name: buzzim-deploy-secret
  namespace: buzzim-deploy
type: Opaque
data:

