apiVersion: v1
kind: Service
metadata:
  labels:
    app: buzz-rtc-svc
  name: buzz-rtc-svc
spec:
  ports:
  - name: 8989-8989
    port: 8989
    protocol: TCP
    targetPort: 8989
    nodePort: 30089
  selector:
    app: buzz-rtc
  sessionAffinity: None
  type: NodePort
